server:
  port: 8001
  
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml
#  type-aliases-package: com.gof.springcloud.entities
#  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  file:
    name: ./log/sample.log

kafka:
  topic:
    group: app1
    house_transaction: house_transaction
  stream:
    katble:
      house_transaction_cnt: house_transaction_cnt

bigquery:
  dataset: 1111
  table: train

spring:
  kafka:
    bootstrap-servers: localhost:9091
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      acks: all
      batch-size: 16384
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-offset-reset: latest

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfigurationdo
  application:
    name: HousePricePrediction-Streaming
      

